@isTest
private class CLP_PaymentCreditCardScheduleBatchTest {
	/*@isTest static void getCreditCardStatus() {
		CLP_PaymentMethodCreditCardScheduleBatch schBatch = new CLP_PaymentMethodCreditCardScheduleBatch();
		Datetime dt = Datetime.now().addMinutes(1);
		String timer = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();

		Test.startTest();
		System.schedule('CLP_PaymentMethodCreditCardScheduleBatch', timer, schBatch);
		Test.stopTest();
		system.assert(timer != null);
	}*/
}