/**
 * CLP_SearchConstant.
 * @author Mulodo Inc.
 * @version 1.0
 * @Description: Search Demand constant
 */
public with sharing class CLP_SearchConstant {
	public static Integer PAGESIZE = 500;
	
	public static String PAYMENT_METHOD = 'payment';
	public static String DEMAND_TYPE = 'demand-type';
	public static String STATUS = 'condition';
	public static String ISSUE_DATE = 'issue-date';
	public static String PERIOD_DATE = 'period-date';
	public static String PRODUCT_CODE = 'product-code';
	public static String PRODUCT_NAME = 'product-name';
	public static String REQUEST_USER = 'request-user';
	public static String DEPARTMENT = 'department';
	public static String SEARCH_ACCOUNT = 'search-account';
	public static String BILLING_SOURCE = 'billing-source';
	public static String STOP_FLAG = 'flag-stop';
}