public class MF_InternalContactSearchObject {
    public Id company;
    public Id branch;
    public Id dept;
    public Id child;
    public String sortBy;
    public String sortOrder;
    public String kname;
    public String kdept;
    public String ktel;
    public String kemail;
    public Integer currentPage;
    public Integer perPage;
    public List<Id> contactId;
    public MF_InternalContactSearchObject() {

    }
}