public class MF_InternalContactsObject {
    public Id Id;
    public String Name;
    public String DeptName;
    public String Phone;
    public String Email;
    public String Comment;
    public Id Chatter;
    public List<String> Activity;
    public String Skype_Account;
    public String EmployeeNo;
    public String Feel;
    public String Description;
    public String Fax;
    public String HomePhone;
    public String MobilePhone;
    public Boolean DoNotCall;
    public Date Birthdate;
    public String OtherPhone;
    public String Title; 
    public String LeadSource;
    public String AssistantName;
    public String AssistantPhone;
    public MF_InternalContactsObject() {

    }
}