public with sharing class WED_Constants {
	public static final String CSSCLASS_INFO = 'info-message';
	public static final String CSSCLASS_SUCCESS = '';
	public static final String CSSCLASS_WARNING = 'warning-message';
	public static final String CSSCLASS_ERROR = 'error-message';
	public static final String CSSCLASS_EXCEPTION = 'exception-message';
	public static final String URL_IMAGESERVER = '{0}/servlet/servlet.ImageServer?id={1}&oid={2}';
	public static final String ANS20_ITEM1 = 'その他（全国紙・その他）';
	public static final String ANS20_ITEM2 = 'TVCM';
	public static final String ANS20_ITEM3 = 'ラジオCM';
	public static final String ANS20_ITEM4 = '交通広告';
	public static final String ANS20_ITEM5 = '特になし';
}